version: '3.4'

services:

  health.monitor:
    image: ${DOCKER_REGISTRY-}healthmonitor
    build:
      context: .
      dockerfile: Health.Monitor/Dockerfile

  svc.a:
    image: ${DOCKER_REGISTRY-}svca
    build:
      context: .
      dockerfile: Svc.A/Dockerfile 

  svc.b:
    image: ${DOCKER_REGISTRY-}svcb
    build:
      context: .
      dockerfile: Svc.B/Dockerfile 

  svc.c:
    image: ${DOCKER_REGISTRY-}svcc
    build:
      context: .
      dockerfile: Svc.C/Dockerfile    

  